# Generated by Django 3.2.7 on 2021-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petonia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Телефон'),
        ),
    ]
