# Generated by Django 3.2.7 on 2021-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petonia_app', '0002_marker_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='telephone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
